### ISSUE TITLE
The CNIL rules that GA is not allowed in France! 

### ISSUE THREAD

**Issue by beaussan** [PostHog/isgoogleanalyticsillegal.com#21]
Here is the (French report), https://www.cnil.fr/fr/utilisation-de-google-analytics-et-transferts-de-donnees-vers-les-etats-unis-la-cnil-met-en-demeure

I will see if I can find news article about it in English too

**Comment by jamesefhawkins** [comment]
Wow - thanks for sharing this. 

@charlescook-ph from a legal perspective, are you ok with us adding this?

**Comment by charlescook-ph** [comment]
Yep - [English article linked at the bottom as well here](https://www.cnil.fr/en/use-google-analytics-and-data-transfers-united-states-cnil-orders-website-manageroperator-comply). Will dig in and learn more - thank you for highlighting @beaussan!

**Comment by corywatilo** [comment]
@smallbrownbike Maps have been updated in [Figma](https://www.figma.com/file/S04saUtQSTfU8E05Thss5S/isgoogleanalyticsillegal.com?node-id=97%3A710).

Button should link [here](https://www.cnil.fr/en/use-google-analytics-and-data-transfers-united-states-cnil-orders-website-manageroperator-comply).
