### ISSUE TITLE
Bug: Alternatives page doesn't load on click 

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/isgoogleanalyticsillegal.com#3]
I’m seeing a bug. If I click the button for alternatives, the alternatives page doesn’t load. It works if I refresh it, but it stays blank otherwise.

Video: https://drive.google.com/file/d/1Tl-d_fLLik6mMuTp08CGOeT8uAgLBbd8/view?usp=sharing

CC @corywatilo

**Comment by jamesefhawkins** [comment]
Which browser are you using? 

I'm not managing to reproduce this...

**Comment by joethreepwood** [comment]
Using Brave. Happens with and without extensions.

I've tried in Chrome and Safari, where it doesn't happen.

We can probably say this is an edge case and ignore if it's limited to Brave tbh.
